# Remember to run `pre-commit autoupdate` to update the hooks
# and `pre-commit install` to install the hooks in your git repository
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.10
    hooks:
      - id: ruff
        args: [--fix] # ruff will automatically fix some issues if possible
      - id: ruff-format

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.7.6
    hooks:
      - id: uv-lock
      - id: uv-export
        args:
          [--frozen, --all-groups, --no-dev, --no-hashes, -o=requirements.txt]
